### ISSUE TITLE
too many 429 error responses

### ISSUE THREAD

**Issue by rrshaban** [polygon-io/issues#303]
**URL**
```

client = RESTClient(POLYGON_API_KEY)

aggs = []
for a in client.list_aggs(
	"AAPL",
	1,
	"minute",
	"2022-01-01",
	"2023-02-03",
	limit=5000,):
  aggs.append(a)
print(aggs)
```

**Result**
`
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.polygon.io', port=443): Max retries exceeded with url: /v2/aggs/ticker/AAPL/range/1/minute/1658156340000/2023-02-03?cursor=bGltaXQ9NTAwMCZzb3J0PWFzYw (Caused by ResponseError('too many 429 error responses'))
`

**Expected Result**

It seems like there is a deeper issue that is being somehow covered up by an implicit retry logic which is then causing this surface issue of "too many retry errors". This is my first touch on the API, following <https://polygon.io/blog/polygon-io-with-python-for-stock-market-data>. 

**Screenshots**
doesn't seem necessary but lmk if needed

**Desktop (please complete the following information):**
 - OS: macOSX 14.1

**Additional context**

`
% python p.py
Traceback (most recent call last):
  File "/Users/razishaban/cs/directory/p/p.py", line 8, in <module>
    for a in client.list_aggs(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/polygon/rest/base.py", line 215, in _paginate_iter
    resp = self._get(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/polygon/rest/base.py", line 121, in _get
    resp = self.client.request(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/request.py", line 77, in request
    return self.request_encode_url(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/request.py", line 99, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/razishaban/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.polygon.io', port=443): Max retries exceeded with url: /v2/aggs/ticker/AAPL/range/1/minute/1658156340000/2023-02-03?cursor=bGltaXQ9NTAwMCZzb3J0PWFzYw (Caused by ResponseError('too many 429 error responses'))
`

**Comment by rrshaban** [comment]
It looks like the API is dialing many times (Polygon Dashboard logs suggest 16 OK and 12 errors) though I've only run the script 3 times. I'm a bit confused as to why.

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. What email is your account under? I'm happy to take a look into this for you. My initial thought is that you may be on the Basic, free plan, which comes with 5 requests per minute. The Python Client auto paginates with list_aggs, and using the "next_url" in the background, but they still count towards your query limit.

**Comment by StasonJatham** [comment]
I have the same issue.
