### ISSUE TITLE
Trying to insert result of Ticker API to mongodb using nodejs

### ISSUE THREAD

**Issue by rmary007** [polygon-io/issues#89]
**URL**
'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page=1&apiKey=xxxxxxxxxx'

**Result**
Error: connect ETIMEDOUT 38.133.177.36:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '38.133.177.36',
  port: 443
}

**Expected Result**
To save all responses into collection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome,firefox
 

**Additional context**
I am trying to insert to my mongodb collection , the response from ticker API. I could able to see its response like page:1, perPage:50, count: 37232 and ticker array.
In want to save tickers array. Here is what I have done in nodejs so far.

var ApiUrl = 'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page=1&apiKey=xxxxxxxxxx';
request(ApiUrl,
  function (err, res, body) {
    if (!err && res.statusCode == 200) {
      let jsonObj = JSON.stringify(res);
      let resp = JSON.parse(JSON.parse(jsonObj).body);

      var totalPageCount = resp.count / resp.tickers.length;
      if (totalPageCount % resp.tickers.length > 0)
        totalPageCount++;
    } else {
      console.log(err);
    }
    for (var k = 1; k <= totalPageCount; k++) {
      var ApiUrlPerPage = 'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page='+k+'&apiKey=xxxxxxxxxx';
      request(ApiUrlPerPage, function (error, response, body) {
        if (!error && response.statusCode == 200) {
          let json = JSON.stringify(response);
          let result = JSON.parse(JSON.parse(json).body);
          for (var j = 0; j < result.tickers.length; j++) {
            var todo = new stockTickerModel({
                ticker: result.tickers[j].name
              },
            );
            // Save it to database
            todo.save(function (err) {
              if (err)
                console.log("Error:" + err);
            })
          }
        } else {
          console.log(error);
        }
      })
    }
  }
)

After executing this, what I am getting is sometime 20k responses are saved sometimes 19k etc. And in my console I frequently gets timed out error as I mentioned above.
Can you please suggest, how can I save all the 37232 records.

**Comment by rmary007** [comment]
> 
> 
> **URL**
> 'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page=1&apiKey=xxxxxxxxxx'
> 
> **Result**
> Error: connect ETIMEDOUT 38.133.177.36:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '38.133.177.36',
> port: 443
> }
> 
> **Expected Result**
> To save all responses into collection.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10
> 
>     * Browser chrome,firefox
> 
> 
> **Additional context**
> I am trying to insert to my mongodb collection , the response from ticker API. I could able to see its response like page:1, perPage:50, count: 37232 and ticker array.
> In want to save tickers array. Here is what I have done in nodejs so far.
> 
> var ApiUrl = 'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page=1&apiKey=xxxxxxxxxx';
> request(ApiUrl,
> function (err, res, body) {
> if (!err && res.statusCode == 200) {
> let jsonObj = JSON.stringify(res);
> let resp = JSON.parse(JSON.parse(jsonObj).body);
> 
> ```
>   var totalPageCount = resp.count / resp.tickers.length;
>   if (totalPageCount % resp.tickers.length > 0)
>     totalPageCount++;
> } else {
>   console.log(err);
> }
> for (var k = 1; k <= totalPageCount; k++) {
>   var ApiUrlPerPage = 'https://api.polygon.io/v2/reference/tickers?sort=ticker&market=STOCKS&page='+k+'&apiKey=xxxxxxxxxx';
>   request(ApiUrlPerPage, function (error, response, body) {
>     if (!error && response.statusCode == 200) {
>       let json = JSON.stringify(response);
>       let result = JSON.parse(JSON.parse(json).body);
>       for (var j = 0; j < result.tickers.length; j++) {
>         var todo = new stockTickerModel({
>             ticker: result.tickers[j].name
>           },
>         );
>         // Save it to database
>         todo.save(function (err) {
>           if (err)
>             console.log("Error:" + err);
>         })
>       }
>     } else {
>       console.log(error);
>     }
>   })
> }
> ```
> 
> }
> )
> 
> After executing this, what I am getting is sometime 20k responses are saved sometimes 19k etc. And in my console I frequently gets timed out error as I mentioned above.
> Can you please suggest, how can I save all the 37232 records.
